@startuml erd
skinparam Linetype ortho
skinparam classFontSize 20
scale 2400 * 2400
hide circle

enum AcceptanceStatus {
    Pending
    Accepted
    Rejected
}

enum Association {
    Sponsor
    Organizer
    Media
    Other
}

enum EmploymentContract {
    DPP
    DPC
    HPP
}

enum EmployeeLevel {
    Basic
    Manager
    CompanyAdministrator
}

enum EventRole {
    Basic
    Organizer
}

enum Gender {
    Female
    Male
    Other
}

enum TaskPriority {
    Low
    Medium
    High
}

enum UserRole {
    User
    Admin
}

enum UserStatus {
    Available
    Unavailable
}

entity user {
    *<u>user_id</u>: <<uuid>>
    ---
    ' Full name. They will log in using their email.
    *name: varchar(255)
    *email: varchar(45)
    *date_of_birth: date
    avatar_path: varchar(255)
    *gender: <<enum Gender>>
    *role: <<enum UserRole>>
    *status <<enum UserStatus>>
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity timesheet {
    *<u>timesheet_id</u>: <<uuid>>
    ---
    *user_id: <<uuid>> (FK user)
    *company_id: <<uuid>> (FK company)
    *event_id: <<uuid>> (FK event)
    *start_date: date
    *end_date: date
    *total_hours: float
    *is_editable: boolean
    ' allows managers to leave notes in case of errors.
    manager_note: text
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity work_day {
    *<u>timesheet_id</u>: <<uuid>>
    *<u>work_date</u>: date
    ---
    *total_hours: float
    comment: text
    *is_editable: boolean
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity event {
    *<u>event_id</u>: <<uuid>>
    ---
    *name: varchar(255)
    description: text
    website: varchar(255)
    *accepts_staff: boolean
    *start_date: date
    *end_date: date
    avatar_path: varchar(255)
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity task {
    *<u>task_id</u>: <<uuid>>
    --
    *event_id: uuid (FK event)
    *creator_id: uuid (FK event_staff)
    *title: text
    description: text
    finished_at: timestamp
    *priority: <<enum TaskPriority>>
    *accepts_staff: boolean
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity assigned_staff {
    *<u>task_id</u>: <<uuid>> (FK task)
    *<u>staff_id</u>: <<uuid>> (FK event_staff)
    decided_by: <<uuid>> (FK event_staff)
    ---
    *status: <<enum AcceptanceStatus>>
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

together {
    entity company {
        *<u>company_id</u>: <<uuid>>
        ---
        *name: varchar(255)
        description: text
        website: varchar(255)
        /' A Company Registration Number.

        Note: Different European countries use different format, some just
                numbers, some letters as well, but they all fit into 16 characters.
        '/
        *CRN: varchar(16)
        /'
        A Value-Added Tax Identification Number.

        Note: China seems to have a longest format with 18 characters.
        '/
        *VATIN: varchar(18)
        *phone: varchar(255)
        *email: varchar(255)
        avatar_path: varchar(255)
        *created_at: timestamp
        *edited_at: timestamp
        deleted_at: timestamp
    }

    /' 
        Normalization for compound type address.
        In case we want to expand some filtering.
        Also normalization.
    '/
    entity address {
        *<u>company_id<u>: <<uuid>>
        ---
        country: varchar(255)
        region: varchar(255)
        city: varchar(255)
        street: varchar(255)
        street_number: varchar(255)
        postal_code: varchar(255)
    }
}

entity associated_company {
    *<u>company_id</u>: <<uuid>>
    *<u>event_id</u>: <<uuid>>
    ---
    *association_type: <<enum Association>>
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity employment {
    *<u>user_id</u>: <<uuid>>
    *<u>company_id</u>: <<uuid>>
    ---
    /' 
        manager_id and company_id give us the manager\'s employment record.
        manager_id is therefore the user ID of the manager.
    '/
    *manager_id: <<uuid>> 
    *hourly_wage: float
    *start_date: date
    *end_date: date
    ' Allows for descriptions of the employment's purpose.
    description: text
    *employment_type: <<enum EmploymentContract>>
    *employee_level: <<enum EmployeeLevel>>
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity event_staff {
    *<u>staff_id</u>: <<uuid>>  
    ---
    *user_id: <<uuid>> (FK user, part of FK employment)
    *company_id: <<uuid>> (FK company, part of FK employment)
    *event_id: <<uuid>> (FK event)
    decided_by: <<uuid>> (FK event_staff)
    *role: <<enum EventRole>>
    *acceptance_status: <<enum AcceptanceStatus>>
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

entity comment {
    *<u>comment_id</u>: <<uuid>>
    ---
    /' 
        Note that the nullability of event_id 
        and task_id is a xor relationship.
        So either event_id is null, and task_id is not null, or the opposite.
        They can\'t both be null, or both not be null.
    '/
    event_id: <<uuid>>
    task_id: <<uuid>>
    *author_id: <<uuid>>
    *content: text
    *created_at: timestamp
    *edited_at: timestamp
    deleted_at: timestamp
}

/'
  Class relations, possibly with labels.
'/
user||..|{employment
timesheet}o..||employment
timesheet||..o{work_day : can\nhave\n >
timesheet}o..||event
employment||..o{event_staff
employment}o..||company
employment|o..o{employment : manages
event||.o{associated_company
company||..o{associated_company
company||..||address : has headquaters at >
company||..o{event_staff
event||..o{event_staff : is organized by >
event||..o{task : can have associated >
event|o...o{comment : can have >
task|o...o{comment : can have >
comment}o..||user : is sent by >
task||..||event_staff : was\ncreated\nby >
task||..o{assigned_staff
assigned_staff}o..||event_staff
assigned_staff||..||event_staff : is\ndecided\nby >
event_staff}o..||event_staff : appointed\n as an\n organizer
@enduml