name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
